<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
<atom:link href="https://www.ethernetservers.com/clients/networkissuesrss.php" rel="self" type="application/rss+xml" />
<title><![CDATA[Ethernet Servers Ltd]]></title>
<description><![CDATA[Ethernet Servers Ltd Network Issues Feed]]></description>
<link>https://www.ethernetservers.com/clients/networkissues.php</link>
<item>
    <title>New Jersey Outage</title>
    <link>https://www.ethernetservers.com/clients/networkissues.php?view=nid82</link>
    <pubDate>Mon, 10 Jul 2023 23:16:00 +0100</pubDate>
    <description><![CDATA[<p>We are aware of a network issue in New Jersey. </p>
<p><strong>UPDATE - 10th July:</strong> <span style="text-decoration: line-through;">Everything is now back online.</span> It is not yet clear what happened. What we know so far is that whilst all New Jersey servers became inaccessible (network), some of those also rebooted. Our upstream provider are conducting an investigation. An RFO (Reason For Outage) will be made available within 24 hours via support ticket. We apologize for the troubles caused.</p>
<p><strong>UPDATE - </strong><strong>10th July</strong><strong>:</strong> It appears the issue has resurfaced. We're working with our upstreams to investigate.</p>
<p><strong>UPDATE @ 23:50 BST - </strong><strong>10th July</strong><strong>:</strong> There is a facility-level issue impacting the whole building. We are awaiting updates.</p>
<p><strong>UPDATE @ 00:05 BST - </strong><strong>11th July</strong><strong>:</strong> We are still awaiting an update from the facility.</p>
<p><strong>UPDATE @ 00:24 BST</strong><strong> - </strong><strong>11th July</strong><strong>:</strong> The most recent update we have from the facility is as follows:</p>
<p>We are currently experiencing a sitewide power issue related to our UPS systems at EWR1. We have site personnel investigating the issue. We have called our UPS vendor who is currently in route to the site to assist us as well. We will send updates every 15 minutes as we make progress on resolution.</p>
<p><strong>UPDATE @ 00:55 BST</strong><strong> - </strong><strong>11th July</strong><strong>:</strong> We continue to await an update from the facility. Our sincere apologies for the downtime here.</p>
<p><strong>UPDATE @ 01:05 BST</strong><strong> - </strong><strong>11th July</strong><strong>:</strong> This has not been officially confirmed by the facility, but another tenant in the facility has advised:</p>
<p><br />We've been informed that an electrical room experienced a fire, was put out by retardant, and the datacenter is in emergency power off status at the requirement of on-site fire fighters.<br /><br />Ethernet Servers cannot verify this information.<br /><br />We will share updates as soon as possible. <br /><br /><strong>UPDATE @ 02:15 BST</strong><strong> - </strong><strong>11th July</strong><strong>:<br /><br /></strong>An isolated fire in an UPS in an electrical room was detected and put out by fire suppression. The local fire department arrived on the scene, and per NEC guidelines and likely local laws and general best practices for firefighters, cut the power to the building. This caused the down -&gt; up -&gt; down cycle noted earlier today. Current state is that datacenter electricians are on site awaiting access to the building to perform repair work to the UPS, but are currently waiting permission from the fire department to enter the building. Once the electrical work is complete, the power will be applied to HVAC to subcool the facility, which will take an estimated 3-4 hours, and at that point, power will be restored to data halls, which will bring our network and servers back online. The datacenter manager gave a best-case ETA of tomorrow morning, July 11th, for power to be restored to data halls.</p>
<p><strong>UPDATE @ 05:12 BST </strong><strong> - </strong><strong>11th July</strong><strong>:<br /><br /></strong>Our data center have shared the following update with us:</p>
<p>Power remains off at the data center per the local Fire Marshall.</p>
<p>After reviewing the site, the Fire Marshall is requiring that we extensively clean the UPS devices and rooms before they will allow us to re-energize the site. We have a vendor at the site currently who will be performing that cleanup. </p>
<p>We will provide an update at 8:00AM EDT unless something significant changes overnight.</p>
<p><strong>UPDATE @ 08:25 BST </strong><strong> - </strong><strong>11th July</strong><strong>:<br /><br /></strong>We have received numerous requests asking of an ETA, but we nor the data center have that information at this time.<br /><br />Ultimately, it is up to the authorities to decide when power may be switched back on, subject to the cleaning/repair process being completed to their satisfaction.</p>
<p><strong>UPDATE @ 12:06 BST </strong><strong> - </strong><strong>11th July</strong><strong>:<br /><br /></strong>I would like to express my deepest apologies for the troubles here. During the ten years I've been running Ethernet Servers, there's never been anything like this happen before. It is a deeply regretful and saddening situation to be in. Whilst there's always spare servers and parts available, it's not normal to factor in spare data center buildings as circumstances like this are extremely rare - something most hosting providers and customers will never experience. <br /><br />Currently, there is still no update from EWR1 / Evocative (the data center), but they previously stated they will provide an update at 8:00AM EDT, which is in an hour. </p>
<p>As soon as more information becomes available, it will be shared here. <br /><br /><strong>UPDATE @ 12:39 BST - 11th July:</strong><br /><br />The building have just shared the following update with us:</p>
<p>We expect the cleanup to take place at 8am and the fire marshall to inspect afterward, We will keep you updated along the way.</p>
<p><strong>UPDATE @ 14:09 BST - 11th July:</strong><br /><br />The building have just shared the following update with us:<br /><br />Our remediation vendor and our team has worked through the night to clean the UPS' at the request of the fire marshal. They have made significant progress and we hope to have the cleaning completed by mid-day, at which time we will engage the fire marshal to review the site.  Following their review, we hope to get a sign off from them so that we can start the reenergizing process. The reenergizing process can take 4-5 hours, as we need to turn up the critical infrastructure prior to any servers. </p>
<p><strong>UPDATE @ 16:29 BST - 11th July:</strong><br /><br />The building have just shared the following update with us:<br /><br />Our cleaning vendor has been working diligently in cleaning the affected areas of the site and is currently around 40% complete. Evocative staff will be meeting with the local township at 2PM EDT to do a walk through of the site to re-energize the facility. We will provide an update after this meeting regarding power restoration status.</p>
<p><strong>UPDATE @ 17:22 BST - 11th July:</strong><br /><br />The building have just shared the following update with us:</p>
<p>The EWR Secaucus data center remains powered down at this time per the fire marshal. We continue to clean and ready the site for final approval by the fire marshal in order to re-energize the facilities critical equipment. Site management, the fire marshal, and electrical contractors will be meeting at 2PM EDT in an attempt to receive approval from the fire marshal to re-energize the site. We do not foresee any issues that would result in not receiving such approval.</p>
<p>Re-energizing critical equipment will take 4-5 hours. After this process, we will be energizing customer circuits and powering on all customer equipment. We will provide updates as to when customers will be allowed in the facility once approved by the fire marshal.</p>
<p><strong>UPDATE @ 19:40 BST - 11th July:</strong><br /><br />The building have just shared the following update with us:</p>
<p>The EWR Secaucus data center remains powered down at this time per the fire marshal. </p>
<p>Site management, the fire marshal, and electrical contractors are currently meeting to review the process of the cleaning effort to get approval from the fire marshal to re-energize the site. </p>
<p>We will update you as soon as the meeting has concluded.</p>
<p><strong>UPDATE @ 21:27 BST - 11th July:</strong><br /><br />The building have just shared the following update with us:</p>
<p>We have just finished the meeting with the fire marshal, electrical inspectors, and our onsite management. We have made great progress cleaning and after reviewing it with the fire marshal, they have asked us to clean additional spaces and they have also asked us to replace some components of the fire system. They have set a time to come back and review these requests at 9am EDT Wednesday. We are working to comply completely with these new requests with these vendors and are bringing in additional cleaning personnel onsite to make the fire marshal's deadline.</p>
<p>In preparation for being able to allow clients onsite, the fire marshal has stated that we need to perform a full test of the fire/life safety systems which will be done after utility power has been restored and fire system components replaced. We have these vendors standing by for this work tomorrow.</p>
<p>Assuming that all goes as planned, the earliest that clients will be allowed back into the site to power up their servers would be late in the day Wednesday.<br /><br /><span style="color: #ff0000;"><strong>We are actively working on deploying new hardware in a different data center to try and get things online sooner for our shared hosting customers, of whom we maintain daily off-site backups and can restore more quickly.</strong></span><br /><br /><span style="color: #ff0000;"><strong>VPS customers, the situation is more complex due to the large number of IP addresses we require, the larger server builds and the sheer amount of data involved. </strong></span></p>
<p><span style="color: #ff0000;"><strong style="color: #000000;">UPDATE @ 22:57 BST - 11th July:<br /><br /></strong><span style="color: #000000;">For our shared hosting customers: we are working on installing the operating system on a new server in a different data center (Equinix) and will begin restoring our backups shortly.<br /><br />For our VPS hosting customers: we will begin deploying new hardware in our Los Angeles facility and offering customers a new VPS in that facility. It will take time and we will provide an update as soon as possible.<br /><br /><span style="color: #ff0000;"><strong>We ask that customers refrain from creating tickets as our priority is on getting everyone back online as quickly as we can, and replying to tickets slows down that process.</strong></span></span></span></p>
<p><strong>UPDATE @ 07:51 BST - 12th July:<br /><br /></strong>The building have shared the following update with us:</p>
<p>The EWR Secaucus data center remains powered down at this time per the fire marshal. We are continuing with our cleanup efforts into the evening and working overnight as we make progress towards our 9AM EDT meeting time with the fire marshal and electrical inspectors in order to reinstate power at the site.</p>
<p>Once we receive approval and utility is restored, we will turn up critical systems. This will take approximately 5 hours. After the critical systems are restored, we will be turning up the carriers and then will start to turn the servers back on.</p>
<p>The fire marshal has requested replacement of the smoke detectors in the affected area as well as a full site inspection of the fire life safety system prior to allowing customers to enter the facility. Assuming that all goes as planned, the earliest that clients will be allowed back into the site to work on their equipment would be late in the day Wednesday.<br /><br /><strong>UPDATE @ 11:38 BST - 12th July:<br /><br /></strong>Unfortunately, the new provider we chose to facilitate our shared hosting customers deployed a server with faulty disk drives...</p>
<p>We no longer consider that a viable move given that we're two hours away from the fire department's inspection and hopeful restoration of power within a few hours of the inspection taking place. </p>
<p><strong>UPDATE @ 15:20 BST - 12th July:</strong></p>
<p>We have not yet received an update from the data center, despite emails being sent to request an update. </p>
<p>As soon as an update is available, it will be shared here.</p>
<p><strong>UPDATE @ 15:29 BST - 12th July:<br /><br /></strong>The latest update from the data center:</p>
<p>I heard the preliminary inspection is good and we are taking steps to energize the property now. </p>
<p>I’m waiting for the official update from DC Ops.  More to come.</p>
<p><strong>UPDATE @ 17:40 BST - 12th July:</strong><br /><br />The latest update from the data center:</p>
<p>We have completed the full site inspection with the fire marshal and the electrical inspector and utility power has been restored to the site. </p>
<p>We are now working to restore critical systems and our onsite team has energized the primary electrical equipment that powers the site. Concurrently, we are beginning work to bring the mechanical plant online. Additional engineers from other facilities are on site this morning to expedite site turn up.</p>
<p>The ETA for bringing up the critical infrastructure systems is approximately 5 hours.</p>
<p><strong>UPDATE @ 18:51 BST - 12th July:</strong><br /><br />The latest update from the data center:</p>
<p>Our onsite team has energized the primary electrical equipment that powers the site, enabling us to bring our mechanical plant online. We are currently cooling the facility.</p>
<p>As we monitor for stability, we are focused on bringing up our electrical systems. In starting this process, we have identified an issue with powering up our fire panel as well as power systems that were powered by UPS3. While this will cause us a delay, we are working with our vendors for remediation.</p>
<p>We are currently at 25% for completion toward bringing the site back online and the revised ETA for bringing up the critical infrastructure systems is approximately 7 hours. We are still planning for an evening time frame when clients will be able to come back on site. We will send out additional information regarding access to the facility and remote hands assistance and we will notify you once client access to the facility is permitted. </p>]]></description>
</item>
</channel>
</rss>